### PR TITLE
Adicionando JavaScript pela branch skills-updates

### PR DESCRIPTION
**Pull request by JonnesBezerra**
I create a new branch and added the JavaScript skill for the exercise from day 2.2 point 8.

### CODE REVIEW

**Comment by JSouza27** [comment]
Isso ae Jonnes, muito bom !!

**Comment by arkyn25** [comment]
Execelent!

**Review by janaolive — COMMENTED** [review]
Muito legal!

**Comment by Breno3B** [comment]
Bom trabalho!

**Pull request merged**
